---
title: "Plano de Ensino"
toc: true
toc-depth: 2
---

As informações oficiais da UC estão disponibilizadas nesta página.

## Ementa

Equações diferenciais ordinárias de primeira ordem e equações diferenciais ordinárias de segunda ordem com coeficientes constantes.

## Conteúdo Programático

- Equações diferenciais ordinárias: definição e classificação de equações diferenciais ordinárias. Teorema da existência e unicidade.

- Equações de primeira ordem. Equações separáveis. Equações lineares. Equações exatas. Fator integrante. Substituição de variáveis. Equações homogêneas e equação de Bernoulli. Aplicações de equações de primeira ordem.

- Equações diferenciais lineares. Operadores diferenciais. Existência e unicidade de soluções. O Wronskiano e a equação homogênea. A equação não homogênea. Redução de ordem.

- Equações lineares com coeficientes constantes. Método de variação de parâmetros. Método de coeficientes a determinar. Aplicações: o oscilador harmônico.

- Equações diferenciais de 2ª ordem; resolução e aplicações.

## Objetivos

<b>Gerais:</b> Fornecer ao(à) estudante um conteúdo pleno de equações diferenciais, em especial, na resolução dessas equações e aplicações na modelagem matemática de fenômenos biológicos, químicos e físicos. Despertar o(a) estudante para a necessidade de aplicar os conteúdos trabalhados em pesquisas científicas, especialmente nas áreas aplicadas às Ciências do Mar.

<b>Específicos:</b> O(A) estudante será capaz de:

- identificar, classificar e resolver as equações diferenciais ordinárias;

- descrever os fenômenos da natureza, especialmente nas áreas biológicas, sociais, econômicas, físicas e engenharias, utilizando equações diferenciais na modelagem matemática desses fenômenos, e quando necessário, resolvê-las;

- aplicar as equações diferenciais;

- assimilar e aplicar os conceitos teóricos e compreender sua inter-relação com as outras áreas das ciências aplicadas;

- atuar em equipes interdisciplinares.

## Metodologia de Ensino

Atividades teóricas, práticas computacionais, leituras dirigidas e listas de exercícios.

## Avaliação

A avaliação será composta por <b>provas</b>, realizadas em sala de aula (<b>peso de 60%</b>), e <b>listas de exercícios</b>, entregues por meio do Moodle (<b>peso de 40%</b>). As datas das provas estão disponíveis no [cronograma](cronograma.qmd), enquanto os prazos para entrega das listas de exercícios podem ser consultados no [Moodle](https://moodlegrad.unifesp.br/) da UC.

A <b>Nota do Período Letivo (NL)</b> será calculada pela média ponderada dessas avaliações, conforme a expressão a seguir:

<div style="text-align: center; font-weight: bold;">
NL = 0,6 × (média aritmética das provas) + 0,4 × (média aritmética das listas de exercícios).
</div>

A aprovação na UC depende do cumprimento simultâneo da <i>frequência mínima</i> e do <i>aproveitamento acadêmico</i>, conforme o Regulamento dos Cursos de Graduação da Unifesp. <b>A frequência mínima exigida é de 75%</b>. <i>O(A) estudante que não cumprir a frequência mínima exigida estará reprovado(a), independentemente da nota obtida</i>.

Para o(a) estudante que cumprir a frequência mínima, o resultado depende da <b>NL</b>:

- se <b>NL &ge; 6,0</b>, o(a) estudante estará <b>aprovado(a)</b> e a nota final será igual a <b>NL</b>;

- se <b>NL < 3,0</b>, o(a) estudante estará <b>reprovado(a) sem direito a exame</b>;

- se <b>3,0 &le; NL &le; 5,9</b>, o(a) estudante <b>terá que se submeter a exame</b>.

A nota final do(a) estudante que tiver de realizar exame será

<div style="text-align: center; font-weight: bold;">
(NL + nota do exame)/2.
</div>

O(A) estudante será <b>aprovado(a)</b> se obtiver <b>nota final maior ou igual a 6,0</b>. Caso contrário, será <b>reprovado(a)</b>.

O(A) estudante que não comparecer ao exame receberá nota <b>0,0 (zero)</b>, o que implicará sua reprovação.

## Bibliografia

<b>Bibliografia Básica:</b>

1. Stewart, J., Clegg, D., & Watson, S. (2022). Cálculo v.2 (6th ed.). Grupo A.
📖 [Consultar livro](https://integrada.minhabiblioteca.com.br/books/9786555584103)

2. Boyce, W. E., DiPrima, R. C., & Meade, D. B. (2024). Equações Diferenciais Elementares e Problemas de Valores de Contorno (12th ed.). Grupo GEN.
📖 [Consultar livro](https://integrada.minhabiblioteca.com.br/books/9788521638841)

3. Çengel, Y. A., & III, W.J. P. (2014). Equações diferenciais. Grupo A.
📖 [Consultar livro](https://integrada.minhabiblioteca.com.br/books/9788580553499)

4. Zill, D. G. (2016). Equações diferenciais: com Aplicações em Modelagem - Tradução da 10ª edição norte-americana (3rd ed.). Grupo A.
📖 [Consultar livro](https://integrada.minhabiblioteca.com.br/books/9788522124022)

5. Leithold, L. Cálculo com Geometria Analítica - Vol. 2, 3ª edição. Editora Harbra.

<b>Bibliografia Complementar:</b>

1. Simmons, G. F.. Cálculo com Geometria Analítica, v. 2. Editora McGraw-Hill.

2. Kaplan, W. (1972). Cálculo avançado, vol. 2. Editora Blucher.
📖 [Consultar livro](https://integrada.minhabiblioteca.com.br/books/9788521216612)

::: {.callout-tip}
## Acesso aos livros

Os links da bibliografia direcionam aos respectivos livros na plataforma **Minha Biblioteca**.

**Antes de utilizá-los, é necessário acessar a plataforma institucional da Unifesp e realizar sua autenticação.**

📚 [Acessar a plataforma Minha Biblioteca](https://biblioteca.unifesp.br/login?redirect=minhabiblioteca)
:::